{{- if .Values.database.create }}
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
    app.kubernetes.io/component: database
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .Values.database.name }}
  ports:
  - port: {{ .Values.secrets.postgres.port }}
    targetPort: {{ .Values.secrets.postgres.port }}
    name: postgres
  type: ClusterIP
{{- end }}
