apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      volumes:
      - name: rest-init-sql
        configMap:
          name: rest-init-sql
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z db 5432; do echo waiting for db; sleep 2; done;']
      - name: init-rest-auth
        image: postgres:15-alpine
        command: ['sh', '-c', 'psql -h db -U supabase_admin -d postgres -f /init.sql']
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: rest-init-sql
          mountPath: /init.sql
          subPath: init.sql
      containers:
      - name: rest
        image: postgrest/postgrest:v13.0.7 #v12.2.12
        ports:
        - containerPort: 3000
          name: rest
        env:
        - name: PGRST_LOG_LEVEL
          value: "info"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        - name: PGRST_OPENAPI_SERVER_PROXY_URI
          value: "http://localhost:8000/rest/v1/"
        - name: PGRST_OPENAPI_SECURITY_ACTIVE
          value: "true"
        - name: PGRST_DB_URI
          value: "postgres://authenticator:your-super-secret-password@db:5432/postgres"
        - name: PGRST_DB_SCHEMAS
          value: "public,storage,graphql_public"
        - name: PGRST_DB_ANON_ROLE
          value: "anon"
        - name: PGRST_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: JWT_SECRET
        - name: PGRST_DB_USE_LEGACY_GUCS
          value: "false"
        - name: PGRST_APP_SETTINGS_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: JWT_SECRET
        - name: PGRST_APP_SETTINGS_JWT_EXP
          value: "3600"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
      - name: swaggerui
        image: swaggerapi/swagger-ui:v5.17.14
        ports:
        - containerPort: 8080
          name: swagger
        env:
        - name: SWAGGER_JSON_URL
          value: "http://localhost:8000/rest/v1/"
        - name: BASE_URL
          value: "/swagger"
        # - name: QUERY_CONFIG_ENABLED
        #   value: "true"
        # - name: API_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: supabase-secrets
        #       key: SERVICE_ROLE_KEY
