apiVersion: v1
kind: Service
metadata:
  name: rest
  namespace: supabase
spec:
  selector:
    app: rest
  ports:
  - port: 3000
    targetPort: 3000
    name: rest
  - port: 8080
    targetPort: 8080
    name: swagger
  type: ClusterIP
