{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  # Database credentials
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgres.user | quote }}
  POSTGRES_HOST: {{ .Values.secrets.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.secrets.postgres.port | quote }}
  POSTGRES_DATABASE: {{ .Values.secrets.postgres.database | quote }}
  
  # JWT configuration
  JWT_SECRET: {{ .Values.secrets.jwt.secret | quote }}
  
  # API Keys
  ANON_KEY: {{ .Values.secrets.keys.anonKey | quote }}
  SERVICE_ROLE_KEY: {{ .Values.secrets.keys.serviceRoleKey | quote }}
  
  # Database URLs
  DATABASE_URL: {{ .Values.secrets.databaseUrls.postgres | quote }}
  STORAGE_DATABASE_URL: {{ .Values.secrets.databaseUrls.storage | quote }}
  
  # Dashboard credentials
  DASHBOARD_USERNAME: {{ .Values.secrets.dashboard.username | quote }}
  DASHBOARD_PASSWORD: {{ .Values.secrets.dashboard.password | quote }}
  
  # Realtime configuration
  SECRET_KEY_BASE: {{ .Values.secrets.realtime.secretKeyBase | quote }}
  
  # Vault encryption
  VAULT_ENC_KEY: {{ .Values.secrets.vault.encKey | quote }}
  
  # Logflare tokens
  LOGFLARE_PUBLIC_ACCESS_TOKEN: {{ .Values.secrets.logflare.publicAccessToken | quote }}
  LOGFLARE_PRIVATE_ACCESS_TOKEN: {{ .Values.secrets.logflare.privateAccessToken | quote }}
  
  # Domain configuration
  DOMAIN: {{ .Values.secrets.domain | quote }}
{{- end }}