apiVersion: v1
kind: ConfigMap
metadata:
  name: db-supavisor-init
  namespace: supabase
data:
  99-supavisor.sql: |
    \set pguser `echo "$POSTGRES_USER"`

    create schema if not exists _supavisor;
# alter schema _supavisor owner to :pguser;
