apiVersion: apps/v1
kind: Deployment
metadata:
  name: supavisor
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supavisor
  template:
    metadata:
      labels:
        app: supavisor
    spec:
      volumes:
      - name: supavisor-init
        configMap:
          name: db-supavisor-init
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z db 5432; do echo waiting for db; sleep 2; done;']
      - name: run-supavisor-init-sql
        image: postgres:15-alpine
        command: ['psql', '-h', 'db', '-U', 'postgres', '-d', 'postgres', '-f', '/sql/99-supavisor.sql']
        env:
        - name: POSTGRES_USER
          value: "supabase_admin"
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: supavisor-init
          mountPath: /sql/
      containers:
      - name: supavisor
        image: supabase/supavisor:2.5.7
        ports:
        - containerPort: 4000
          name: api
        - containerPort: 5432
          name: postgres
        - containerPort: 6543
          name: transaction
        env:
        - name: PORT
          value: "4000"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "postgres"
        - name: DATABASE_URL
          value: "postgres://supabase_admin:your-super-secret-password@db:5432/postgres"
        - name: CLUSTER_POSTGRES
          value: "true"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: SECRET_KEY_BASE
        - name: VAULT_ENC_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: VAULT_ENC_KEY
        - name: API_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: JWT_SECRET
        - name: METRICS_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: JWT_SECRET
        - name: REGION
          value: "local"
        - name: ERL_AFLAGS
          value: "-proto_dist inet_tcp"
        - name: supavisor_TENANT_ID
          value: "tenant"
        - name: supavisor_DEFAULT_POOL_SIZE
          value: "15"
        - name: supavisor_MAX_CLIENT_CONN
          value: "100"
        - name: supavisor_POOL_MODE
          value: "transaction"
        - name: DB_POOL_SIZE
          value: "5"
        command:
        - "/bin/sh"
        - "-c"
        - "/app/bin/migrate && /app/bin/server"
        # livenessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: 4000
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: 4000
        #   initialDelaySeconds: 10
        #   periodSeconds: 5