apiVersion: v1
kind: Service
metadata:
  name: supavisor
  namespace: supabase
spec:
  selector:
    app: supavisor
  ports:
  - port: 4000
    targetPort: 4000
    name: api
  - port: 5432
    targetPort: 5432
    name: postgres
  - port: 6543
    targetPort: 6543
    name: transaction
  type: ClusterIP
