{{- if .Values.kong.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kong.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.kong.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kong.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kong.name }}
        {{- toYaml .Values.commonLabels | nindent 8 }}
        app.kubernetes.io/component: api-gateway
    spec:
      initContainers:
      - name: template-kong-config
        image: "{{ .Values.kong.initContainer.image.repository }}:{{ .Values.kong.initContainer.image.tag }}"
        command:
        - sh
        - -c
        - |
          # Replace environment variables in kong template
          export SUPABASE_ANON_KEY="${ANON_KEY}"
          export SUPABASE_SERVICE_KEY="${SERVICE_ROLE_KEY}"
          export DASHBOARD_USERNAME="${DASHBOARD_USERNAME}"
          export DASHBOARD_PASSWORD="${DASHBOARD_PASSWORD}"
          
          # Simple variable substitution
          sed -e "s|\$SUPABASE_ANON_KEY|${SUPABASE_ANON_KEY}|g" \
              -e "s|\$SUPABASE_SERVICE_KEY|${SUPABASE_SERVICE_KEY}|g" \
              -e "s|\$DASHBOARD_USERNAME|${DASHBOARD_USERNAME}|g" \
              -e "s|\$DASHBOARD_PASSWORD|${DASHBOARD_PASSWORD}|g" \
              /kong-template/kong.yml > /kong-config/kong.yml
        env:
        - name: ANON_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: ANON_KEY
        - name: SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: SERVICE_ROLE_KEY
        - name: DASHBOARD_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: DASHBOARD_USERNAME
        - name: DASHBOARD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: DASHBOARD_PASSWORD
        volumeMounts:
        - name: kong-template
          mountPath: /kong-template
        - name: kong-processed
          mountPath: /kong-config
      containers:
      - name: kong
        image: "{{ .Values.kong.image.repository }}:{{ .Values.kong.image.tag }}"
        imagePullPolicy: {{ .Values.kong.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.kong.containerPorts.http }}
          name: http
        - containerPort: {{ .Values.kong.containerPorts.https }}
          name: https
        env:
        - name: KONG_LOG_LEVEL
          value: {{ .Values.kong.config.logLevel | quote }}
        - name: KONG_DATABASE
          value: {{ .Values.kong.config.database | quote }}
        - name: KONG_DECLARATIVE_CONFIG
          value: {{ .Values.kong.config.declarativeConfig | quote }}
        - name: KONG_DNS_ORDER
          value: {{ .Values.kong.config.dnsOrder | quote }}
        - name: KONG_PLUGINS
          value: {{ .Values.kong.config.plugins | quote }}
        - name: KONG_NGINX_PROXY_PROXY_BUFFER_SIZE
          value: {{ .Values.kong.config.proxyBufferSize | quote }}
        - name: KONG_NGINX_PROXY_PROXY_BUFFERS
          value: {{ .Values.kong.config.proxyBuffers | quote }}
        {{- if .Values.kong.resources }}
        resources:
          {{- toYaml .Values.kong.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: kong-processed
          mountPath: /home/kong
      volumes:
      - name: kong-template
        configMap:
          name: kong-config
      - name: kong-processed
        emptyDir: {}
{{- end }}
