apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
  namespace: supabase
type: Opaque
stringData:
  POSTGRES_PASSWORD: "your-super-secret-password"
  JWT_SECRET: "your-super-secret-jwt-token-with-at-least-32-characters-long"
  ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE"
  SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q"

  DATABASE_URL: "postgres://postgres:your-super-secret-password@db:5432/postgres"
  STORAGE_DATABASE_URL: "postgres://supabase_admin:your-super-secret-password@db:5432/postgres"
  DASHBOARD_USERNAME: "supabase"
  DASHBOARD_PASSWORD: "supabase"
  SECRET_KEY_BASE: "your-super-secret-key-base-with-at-least-64-characters-long-for-realtime"
  VAULT_ENC_KEY: "your-vault-encryption-key-with-at-least-32-characters-long"
  LOGFLARE_PUBLIC_ACCESS_TOKEN: "your-logflare-public-token"
  LOGFLARE_PRIVATE_ACCESS_TOKEN: "your-logflare-private-token"
  DOMAIN: "localhost"
