apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      serviceAccountName: vector
      containers:
      - name: vector
        image: timberio/vector:0.28.0-alpine #0.50.0-alpine
        args:
          - --config
          - /etc/vector/vector.yml
        ports:
        - containerPort: 9001
          name: api
        securityContext:
          readOnlyRootFilesystem: false
        env:
        - name: LOGFLARE_PUBLIC_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: LOGFLARE_PUBLIC_ACCESS_TOKEN
        - name: VECTOR_SELF_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VECTOR_SELF_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VECTOR_SELF_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: config
          mountPath: /etc/vector
          readOnly: true
        - name: data
          mountPath: /tmp/vector
        - name: var-log
          mountPath: /var/log
          readOnly: true
        - name: var-lib
          mountPath: /var/lib
          readOnly: true
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 9001
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 9001
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: vector-config
      - name: data
        emptyDir: {}
      - name: var-log
        hostPath:
          path: /var/log
      - name: var-lib
        hostPath:
          path: /var/lib
